[package]
name = "BookingSystem"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
booking_system_types = { path = "./booking_system_types" }
rocket = "0.4.11"
